
service: server
frameworkVersion: '3'
plugins: 
  - serverless-domain-manager

provider:
  name: aws
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  runtime: nodejs12.x

custom:
  customDomain:
    domainName: playlinq.io
    certificateArn: arn:aws:acm:us-east-1:630062971847:certificate/3f5a1b8c-9855-47ff-b038-89170d9699ef
    basePath: ''
    stage: ${self:provider.stage}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
