
service: server
frameworkVersion: '3'

provider:
  name: aws
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
      - httpApi:
          path: /users/create
          method: get
