
service: server
frameworkVersion: '3'
plugins: 
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  memorySize: 2048
  stage: dev
  timeout: 15
  region: us-east-1
  runtime: nodejs16.x

custom:
  customDomain:
    domainName: playlinq.io
    # certificateArn: arn:aws:acm:us-east-1:630062971847:certificate/3f5a1b8c-9855-47ff-b038-89170d9699ef
    certificateName: 'arn:aws:acm:us-east-1:630062971847:certificate/3f5a1b8c-9855-47ff-b038-89170d9699ef'
    basePath: ''
    stage: ${self:provider.stage}

functions:
  hello:
    handler: handlers/hello.hello
    events:
      - http:
          path: /hello
          method: get

  token:
    handler: handlers/token.tokenSign
    events:
      - http:
          path: /jwt
          method: get

  genre:
    handler: handlers/genre.fetchGenre
    events:
      - http:
          path: /genre
          method: post

  recent:
    handler: handlers/recentSongs.fetchRecentSongs
    events:
      - http:
          path: /recent
          method: get

  library:
    handler: handlers/library.fetchLibrary
    events:
      - http:
          path: /library
          method: get
  
  rotation:
    handler: handlers/rotation.fetchRotation
    events:
      - http:
          path: /rotation
          method: get
  
  recommendations:
    handler: handlers/recommendations.fetchRecommendations
    events:
      - http:
          path: /recommendations
          method: get